### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by mbergen** [Felerius/findminhs#1]
Hi there,
we wondered under what kind of license this solver is published, as there is currently no information about the license in this repository.
We would like to use and maybe adapt the solver in another project, but are limited to open source dependencies (with an appropriate license).
Can you clarify under what license this solver is available or whether you plan to make it available under a specific license?

Thank you in advance.

**Comment by Felerius** [comment]
Sorry for the missing license, I missed that when publishing the repo. I've put the solver and everything else under the MIT license, which should probably work for you, right?

**Comment by mbergen** [comment]
Yes, MIT is perfect. Thank you very much!
